import type { Task } from "@/src/features/tasks-board/types";
import type { WeekDays } from "@/src/types/common";

const ALL: WeekDays[] = [
  "sunday",
  "monday",
  "tuesday",
  "wednesday",
  "thursday",
  "friday",
  "saturday",
];

type TemplatePack = {
  id: string;
  title: string;
  desc: string;
  recommendedFor: string[];
  tasks: Omit<Task, "id" | "checked" | "order">[];
};

export const TEMPLATE_PACKS: TemplatePack[] = [
  {
    id: "minimal",
    title: "Minimal Daily Routine",
    desc: "Start simple — a reliable base routine.",
    recommendedFor: ["Everyone", "Busy people", "Habit building"],
    tasks: [
      {
        title: "Plan the day",
        desc: "5 minutes: top 3 priorities + schedule.",
        tags: [{ id: "planning", label: "Planning" }],
        color: "zinc",
        line: 1,
        effort: 1,
        weekly: true,
        days: ALL,
      },
      {
        title: "Deep work (60 min)",
        desc: "Focus session — no distractions.",
        tags: [{ id: "focus", label: "Focus" }],
        color: "indigo",
        line: 1,
        effort: 5,
        weekly: true,
        days: ALL,
      },
      {
        title: "Inbox quick check",
        desc: "10–15 minutes: only important messages.",
        tags: [{ id: "admin", label: "Admin" }],
        color: "slate",
        line: 2,
        effort: 2,
        weekly: true,
        days: ALL,
      },
      {
        title: "Learning (20 min)",
        desc: "Article / video / notes — continuous growth.",
        tags: [{ id: "learning", label: "Learning" }],
        color: "teal",
        line: 2,
        effort: 3,
        weekly: true,
        days: ALL,
      },
      {
        title: "Walk / Stretch",
        desc: "Short movement break to reset energy.",
        tags: [{ id: "health", label: "Health" }],
        color: "green",
        line: 3,
        effort: 2,
        weekly: true,
        days: ALL,
      },
      {
        title: "Daily reflection",
        desc: "3 lines: what worked, what didn’t, tomorrow.",
        tags: [{ id: "personal", label: "Personal" }],
        color: "rose",
        line: 3,
        effort: 2,
        weekly: true,
        days: ALL,
      },
    ],
  },

  {
    id: "developer",
    title: "Developer Workflow",
    desc: "Balance shipping, learning, and health.",
    recommendedFor: ["Developers", "Creators", "Product builders"],
    tasks: [
      {
        title: "Ship something",
        desc: "One meaningful change or PR daily.",
        tags: [{ id: "work", label: "Work" }],
        color: "blue",
        line: 1,
        effort: 5,
        weekly: true,
        days: ALL,
      },
      {
        title: "Code review",
        desc: "Review 1–2 PRs or refactor a section.",
        tags: [{ id: "work", label: "Work" }],
        color: "cyan",
        line: 1,
        effort: 3,
        weekly: true,
        days: ALL,
      },
      {
        title: "Deep focus block",
        desc: "90 minutes no meetings, pure build time.",
        tags: [{ id: "focus", label: "Focus" }],
        color: "indigo",
        line: 1,
        effort: 5,
        weekly: true,
        days: ALL,
      },
      {
        title: "Learning (30 min)",
        desc: "Docs / article / test experiment.",
        tags: [{ id: "learning", label: "Learning" }],
        color: "teal",
        line: 2,
        effort: 3,
        weekly: true,
        days: ALL,
      },
      {
        title: "Inbox / messages",
        desc: "15 min admin cleanup to stay sharp.",
        tags: [{ id: "admin", label: "Admin" }],
        color: "slate",
        line: 2,
        effort: 2,
        weekly: true,
        days: ALL,
      },
      {
        title: "Stretch + walk",
        desc: "Reset posture, reduce tension.",
        tags: [{ id: "health", label: "Health" }],
        color: "green",
        line: 3,
        effort: 2,
        weekly: true,
        days: ALL,
      },
    ],
  },

  {
    id: "student",
    title: "Student Workflow",
    desc: "Build consistency in study and review.",
    recommendedFor: ["Students", "Exam preparation", "Courses"],
    tasks: [
      {
        title: "Study block",
        desc: "60–90 minutes focused studying.",
        tags: [{ id: "study", label: "Study" }],
        color: "fuchsia",
        line: 1,
        effort: 5,
        weekly: true,
        days: ALL,
      },
      {
        title: "Homework / assignments",
        desc: "Finish the most important assignment.",
        tags: [{ id: "study", label: "Study" }],
        color: "violet",
        line: 1,
        effort: 3,
        weekly: true,
        days: ALL,
      },
      {
        title: "Review notes",
        desc: "15–20 minutes recap & flashcards.",
        tags: [{ id: "learning", label: "Learning" }],
        color: "teal",
        line: 2,
        effort: 2,
        weekly: true,
        days: ALL,
      },
      {
        title: "Practice test",
        desc: "Solve 10 questions daily.",
        tags: [{ id: "practice", label: "Practice" }],
        color: "amber",
        line: 2,
        effort: 3,
        weekly: true,
        days: ALL,
      },
      {
        title: "Short walk",
        desc: "10 min reset and clear head.",
        tags: [{ id: "health", label: "Health" }],
        color: "green",
        line: 3,
        effort: 1,
        weekly: true,
        days: ALL,
      },
      {
        title: "Plan tomorrow",
        desc: "What to study + when (5 min).",
        tags: [{ id: "planning", label: "Planning" }],
        color: "zinc",
        line: 3,
        effort: 1,
        weekly: true,
        days: ALL,
      },
    ],
  },
];
