export const TASKS_BOARD_TOUR_STEPS: TourStep[] = [
  {
    id: "week-widget",
    title: "Navigate Weeks",
    desc: "Use this widget to move between weeks. Your tasks are shown per selected week.",
    target: "[data-tour='week-widget']",
    placement: "left",
  },
  {
    id: "weekday-tabs",
    title: "Weekdays",
    desc: "Switch between days to see tasks scheduled for that day.",
    target: "[data-tour='weekday-tabs']",
    placement: "bottom",
  },
  {
    id: "lines-board",
    title: "Priority Lines",
    desc: "Tasks are grouped by Line 1/2/3. Line 1 is most important.",
    target: "[data-tour='lines-board']",
    placement: "top",
  },
  {
    id: "drag-handle",
    title: "Reorder Tasks",
    desc: "Drag tasks by the handle to reorder within a line.",
    target: "[data-tour='drag-handle']",
    placement: "bottom",
  },
  {
    id: "check-button",
    title: "Complete Tasks",
    desc: "Mark tasks as done for this day. Completion is tracked daily in analytics.",
    target: "[data-tour='check-button']",
    placement: "right",
  },
  {
    id: "create-task",
    title: "Create Tasks",
    desc: "Create weekly or ranged tasks, assign a line, color, and tags.",
    target: "[data-tour='create-task']",
    placement: "bottom",
  },
  {
    id: "manage-tasks",
    title: "Manage Tasks",
    desc: "Edit or delete any task anytime from here.",
    target: "[data-tour='manage-tasks']",
    placement: "left",
  },
  {
    id: "analytics",
    title: "Analytics",
    desc: "View completion, streaks, timing, and suggestions based on your behavior.",
    target: "[data-tour='analytics']",
    placement: "left",
  },
];

export const MOBILE_TASKS_BOARD_TOUR_STEPS: TourStep[] = [
  {
    id: "week-widget",
    title: "Navigate Weeks",
    desc: "Use this widget to move between weeks. Your tasks are shown per selected week.",
    target: "[data-tour='mb:week-widget']",
    placement: "bottom",
  },
  {
    id: "lines-board",
    title: "Priority Lines",
    desc: "Tasks are grouped by Line 1/2/3. Line 1 is most important.",
    target: "[data-tour='mb:lines-board']",
    placement: "bottom",
  },
  {
    id: "drag-handle",
    title: "Reorder Tasks",
    desc: "Drag tasks by the handle to reorder within a line.",
    target: ".mobile [data-tour='drag-handle']",
    placement: "left",
  },
  {
    id: "check-button",
    title: "Complete Tasks",
    desc: "Mark tasks as done for this day. Completion is tracked daily in analytics.",
    target: ".mobile [data-tour='check-button']",
    placement: "right",
  },
  {
    id: "create-task",
    title: "Create Tasks",
    desc: "Create weekly or ranged tasks, assign a line, color, and tags.",
    target: "[data-tour='mb:create-task']",
    placement: "left",
  },
  {
    id: "manage-tasks",
    title: "Manage Tasks",
    desc: "Edit or delete any task anytime from here.",
    target: "[data-tour='mb:manage-tasks']",
    placement: "left",
  },
  {
    id: "analytics",
    title: "Analytics",
    desc: "View completion, streaks, timing, and suggestions based on your behavior.",
    target: "[data-tour='mb:analytics']",
    placement: "left",
  },
];

export const ANALYTICS_TOUR_STEPS: TourStep[] = [
  {
    id: "range-controls",
    title: "Date Range Selection",
    desc: "Switch between Day, Week, and Month views to analyze tasks for different time periods.",
    target: "[data-tour='range-controls']",
    placement: "bottom",
  },
  {
    id: "filters-bar",
    title: "Filter Data",
    desc: "Filter analytics by task line, tag, or completion status to focus on specific subsets.",
    target: "[data-tour='filters-bar']",
    placement: "bottom",
  },
  {
    id: "score-card",
    title: "Overall Score",
    desc: "Your completion score shows performance against target. Track progress over time.",
    target: "[data-tour='score-card']",
    placement: "bottom",
  },
  {
    id: "compare-panel",
    title: "Period Comparison",
    desc: "See how your performance compares to the previous period (day, week, or month).",
    target: "[data-tour='compare-panel']",
    placement: "bottom",
  },
  {
    id: "forecast-panel",
    title: "Completion Forecast",
    desc: "Predicts future completion based on current trends and historical data.",
    target: "[data-tour='forecast-panel']",
    placement: "bottom",
  },
  {
    id: "summary-cards",
    title: "Key Metrics",
    desc: "Detailed breakdown of scheduled, completed, missed tasks, and timing statistics.",
    target: "[data-tour='summary-cards']",
    placement: "bottom",
  },
  {
    id: "daily-trend-chart",
    title: "Daily Trend",
    desc: "Visualize completion patterns day by day. Hover to see detailed stats for each day.",
    target: "[data-tour='daily-trend-chart']",
    placement: "bottom",
  },
  {
    id: "completion-donut",
    title: "Completion Distribution",
    desc: "See what percentage of tasks are completed, missed, or pending.",
    target: "[data-tour='completion-donut']",
    placement: "bottom",
  },
  {
    id: "timing-bar-chart",
    title: "Timing Analysis",
    desc: "Analyze when tasks are typically completed during the day.",
    target: "[data-tour='timing-bar-chart']",
    placement: "bottom",
  },
  {
    id: "line-stacked-bar",
    title: "Line Performance",
    desc: "Compare completion rates across different priority lines (1, 2, 3).",
    target: "[data-tour='line-stacked-bar']",
    placement: "bottom",
  },
  {
    id: "tag-completion-chart",
    title: "Tag Performance",
    desc: "See completion rates for different task tags to identify strengths and weaknesses.",
    target: "[data-tour='tag-completion-chart']",
    placement: "bottom",
  },
  {
    id: "weekday-habit-chart",
    title: "Weekly Patterns",
    desc: "Identify which days of the week you're most productive and consistent.",
    target: "[data-tour='weekday-habit-chart']",
    placement: "bottom",
  },
  {
    id: "insights-panel",
    title: "Personalized Insights",
    desc: "AI-powered insights and suggestions to improve your productivity.",
    target: "[data-tour='insights-panel']",
    placement: "bottom",
  },
  {
    id: "export-panel",
    title: "Share & Export",
    desc: "Generate shareable reports or export analytics data for external analysis.",
    target: "[data-tour='export-panel']",
    placement: "bottom",
  },
  {
    id: "tag-effectiveness-table",
    title: "Tag Effectiveness",
    desc: "Detailed table showing completion statistics and average times for each tag.",
    target: "[data-tour='tag-effectiveness-table']",
    placement: "top",
  },
];
